config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :profilelinks
    root 'games#index' 
    
    get 'login' => 'login_sessions#new'
    get 'login' => 'login_sessions#create'
    get 'logout' => 'login_sessions#destroy'
    post 'login' => 'login_sessions#create'
	
	get 'signup' => 'users#new'
    
    get 'privacy' => 'staticpages#privacy'
  	resources :games
    resources :users, :path => "players"
    get 'allparties' => 'users#allparties'
	resources :login_sessions
    resources :tags
    resources :parties do 
    resources :messages
    end
    resources :searches
    resources :profilelinks
    
    get '*path' => redirect('/')
    

end

app/models/user.rb
class User < ActiveRecord::Base
    mount_uploader :avatar, AvatarUploader
    
    validates_processing_of :avatar
validate :image_size_validation
            
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    validates :name, presence: true, :length => { :within => 3..30}
    validates :email, presence: true, uniqueness: true, length: { maximum: 50 }
    
    validates :about, length: { maximum: 80 }
    validates :longdesc, length: { maximum: 175 }
    
    has_and_belongs_to_many :games
    has_and_belongs_to_many :tags
    has_and_belongs_to_many :parties
    has_many :party_options
    has_many :donations
    has_many :messages
    
    has_many :profilelinks
    accepts_nested_attributes_for :profilelinks
    
private
  def image_size_validation
    errors[:avatar] << "should be less than 500KB" if avatar.size > 0.5.megabytes
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
 	before_action :logged_in_user, only: [:edit, :update]
      before_action :correct_user,   only: [:edit, :update]

  # GET /users
  # GET /users.json
  def index
      @users = User.search(params[:search])
  end

  # GET /users/1
  # GET /users/1.json
  def show
      set_user
  end
    
    def allparties
        @user = current_user
        render :allparties 
    end

  # GET /users/new
  def new
	  if logged_in? 
#		  redirect_to current_user
		  respond_to do |format|
              flash[:warning] = "You already have an account. Here it is:"
              format.html {redirect_to current_user}
			format.json { render :show, status: :created, location: current_user }
		  end
		  # Maybe throw an error here?
	  else
		  @user = User.new
	  end
  end

  # GET /users/1/edit
  def edit
      set_user
  end

	# POST /users
	# POST /users.json
	def create
		if logged_in?
			respond_to do |format|
		  	format.html { redirect_to current_user, notice: 'You\'re already logged in mate. ' }
			format.json { render :show, status: :created, location: current_user }
		  end
		else
			@user = User.new(user_params)
		@user.email = @user.email.downcase
		
		respond_to do |format|
            if @user.save  
 ExampleMailer.sign_up_welcome(@user).deliver_now
				format.html { redirect_back_or 
                    }
            
				format.json { render :show, status: :created, location: @user }
                flash[:success] = "Welcome!"
				log_in @user
			else
				format.html { render :new }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
		end
		
	end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        
        format.html { redirect_to @user }
          flash[:success] = "Nice, updates made"
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
        @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
        params.require(:user).permit(:name, :email, :password, :avatar, :allow_donation, :income, :longdesc, :about, profilelinks_attributes: [:id, :name, :url], game_ids: [], tag_ids: [], party_options_ids: [],  game_memberships_attributes: [ :id, :game_id ],  party_options_attributes: [ :id, :content, :name, :price, :length ],  user_tags_attributes: [ :id, :tag_id ])
    end
    #confirms a logged-in user
        def logged_in_user
      unless logged_in?
          store_location #links to helper function
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
        # Confirms the correct user. Make this a concerns?
    def correct_user
    unless @user == current_user
      #@user = User.find(params[:id])
        redirect_to(root_url, notice: 'That was an error! Submit an issue here: <provide a link>' ) 
        #unless @user == current_user
        #change root_url to the stored_location function??
    end
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def findparties
        user = @user
        
        if logged_in? && user.id == current_user.id && user.parties.present?
            
        findparties = user.parties.each
     end
 end    
end #end user helper

app/views/users/_form.erb
<!--- complete, all features form. Now only used on edit -->
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
        
      <h3><%= pluralize(@user.errors.count, "error") %>, oh no:</h3>

        <ul><p class="text-warning">
<% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </p>
      </ul>
    </div>
  <% end %>

<form role="form">
  <div class="form-group">

      <div class="col-xs-12 col-sm-6 col-lg-4">
          <div class="field">
    *<%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
      <div class="field">
          *<%= f.label :email %><br>
    <%= f.text_field :email  %>
  </div>
  <div class="field">
    *<%= f.label :password  %><br>
      <%= f.password_field :password %>
      <p class="smalltext">8 characters, one uppercase and one lowercase</p>
      <p class="smalltext">*required for signup</p>
      
  </div>
    
    </div> 
    
      
      
<div class="col-xs-12 col-sm-6 col-lg-4">
<h3>What games do you play?</h3>
 <%= f.collection_check_boxes :game_ids, Game.all, :id, :name do |b| %>
    <div class="collection-check-box">
      <%= b.check_box %>
      <%= b.label %>
        <!--- make this maintain values on update --></div>
        <% end %>
    </div>

    <div class="col-xs-12 col-sm-6 col-lg-4">
<!--Tag your profile:-->
<h3>I'm looking to be ...</h3>

    <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name do |c| %>
    <div class="collection-check-box">
      <%= c.check_box %>
      <%= c.label %>
        </div>
        <% end %>
        
</div>
 <div class="col-xs-12">

     <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>

  <div class="field">
      <h4><%= f.label "Intro" %></h4>
      <p>Tell us about yourself! This shows up in search results.</p>
      <%= f.text_area :about %>
      <span class="smalltext"><span id="chars">80</span> characters remaining</span>
      <h4>Biography </h4>
      <%= f.text_area :longdesc %>
    </div>

  </div>
</div>    <div class="col-xs-12 actions">
    <%= f.submit "Done", class: "btn btn-primary" %>
    </div>


      </form>

<% end %>

app/views/users/_formOLD.html.erb
<!--- complete, all features form. Now only used on edit -->

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
        
      <h3><%= pluralize(@user.errors.count, "error") %>, oh no:</h3>

        <ul><p class="text-warning">
<% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </p>
      </ul>
    </div>
  <% end %>

<form role="form">
  <div class="form-group">
<!--- show only on new -->      

<div class="col-xs-12">
    <a href="#em-pw-edit" data-toggle="collapse" role="button" class="btn btn-default">Change email address or password <span class="glyphicon glyphicon-pencil
"></span></a>
         <div id="em-pw-edit" class="collapse">
      <div class="field">
          <%= f.label :email %><br>
    <%= f.text_field :email  %>
  </div>
  <div class="field">
    <%= f.label :password  %><br>
      <%= f.password_field :password %>
      <p class="smalltext">8 charachters, one uppercase and one lowercase</p>
  </div>
    
    </div> 
    
               </div>
 
      <div class="col-xs-12 col-sm-6 col-lg-4">

             
            <h2>About you</h2>

      <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

     <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>

  <div class="field">
      <h4><%= f.label "Intro" %></h4>
      <p>Tell us about yourself! This shows up in search results.</p>
      <%= f.text_area :about %>
      <span class="smalltext"><span id="chars">80</span> characters remaining</span>
      <h4>Biography </h4>
      <%= f.text_area :longdesc %>
    </div>
          <div class="field">
   
              <h2>Social links</h2>
              <%= link_to "New Profile Link", new_profilelink_path %>               
          </div>
  </div>
      
      
<div class="col-xs-12 col-sm-6 col-lg-4">
    <br>
<h3>What games do you play?</h3>
 <%= f.collection_check_boxes :game_ids, Game.all, :id, :name do |b| %>
    <div class="collection-check-box">
      <%= b.check_box %>
      <%= b.label %>
        <!--- make this maintain values on update --></div>
        <% end %>
    </div>

    <div class="col-xs-12 col-sm-6 col-lg-4">
<!--Tag your profile:-->
<h3>I'm looking to...</h3>

        
    <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name do |c| %>
    <div class="collection-check-box">
      <%= c.check_box %>
      <%= c.label %>
        </div>
        <% end %>
        
<h3>Allow donation?</h3>
        <% @labels_donate = ["Yes", "No"] %>
        <%= f.collection_select :allow_donation, @labels_donate, :to_s, :to_s %> 
</div>

</div>
    <div class="col-xs-12 actions">
      <%= f.submit "Save changes", class: "btn btn-primary" %>
        <%= link_to 'Cancel', @user, class: "btn btn-danger" %>
    </div>
      </form>

<% end %>

app/views/users/_gamelist.html.erb
<div class="games-section">
    <% if @user.games.present? %>
<div class="profile-games-title row">
    <h2>Games I play:</h2>
    </div>
    
    <% gamestoshow = 10 %>
    
    <% c = @user.games.all.limit(gamestoshow) %> 
    
    <% c.each do |u| %> 
    <div class="profile-badge col-xs-6 col-sm-4 col-md-3 col-lg-2">
        
        <div class="user-type">
        <%= link_to u.name, game_path(u.slug) %>
            
        </div>

    <label class="game-label-cover">
    <div id="game-panel" class="select-panel game-selector">
        
        <div class="game-pic">
            <% image_tag u.game_picture, class: "game-pic" %>
            <img src="<%= u.image_url %>">
        </div>


</div>
    </label>
    
</div>
<% end %>
<% end %>
    
    
    
    <% unless @user.games.empty? %>
    <% if @user.games.count > gamestoshow %> 
    <div class="profile-badge col-sm-6">

                <div class="user-type">

        </p>Plus <%= @user.games.count - gamestoshow %> more</p>

</div>
    <label class="game-label-cover">

        <div class="game-pic">
<span class="">+</span>
</div>
</label>

</div>
    <% else %>
    
    <% end %>
    <% end %>
</div>

app/views/users/_linkslist.html.erb
<div class="profilelinks">
            <% if logged_in? %>
<% if @user.id == current_user.id %>
            <% @user.profilelinks.each do |c| %>
    <div class="col-xs-12">
    <span class="spacer"><%= link_to c.name, c.url, class: "btn btn-default" %></span>
            <span class="spacer"><%= link_to "Edit",  edit_profilelink_path(c) %></span>
            <span class="spacer"><%= link_to "Delete",  profilelink_path(c), method: :delete %></span>
        </div>        
    <% end %>
    
    <%= link_to "Add a new social link", new_profilelink_path, class: "btn btn-default" %>
    
            <% else %>
    <!---- user's own links --->
    
      <% @user.profilelinks.each do |m| %>
    <span class="spacer"><%= link_to m.name, m.url, class: "btn btn-default" %></span>

            <% end %>
    <% end %>
              
    <% else %>
    <!--- public links -->
      <% @user.profilelinks.each do |n| %>
                
    <span class="spacer"><%= link_to n.name, n.url, class: "btn btn-default" %></span>
        <% end %>
    <% end %>
        </div>

app/views/users/_listparties.html.erb
<div class="activeparties col-xs-12">
    <% if findparties.present? %>
            
    <h6>Active sessions have at least one message.</h6>
<% findparties.each do |ap| %>
    
    <% unless ap.status.present? %>
    <% if ap.messages.count > @showmessages %>
    
        <% if ap.messages.count > 0 %>
        <a class="btn btn-primary each-party" href="<%= party_path(ap) %>">
        <p class="largetext">
            
        <% ap.users.each do |pu| %> 
            
        <%= pu.name %>
            
            <% unless pu == ap.users.last %>
            and
            <% end %>
            
        <% end %> <!-- end each user -->
        's session
            <span class="badge">
                            <%= ap.messages.count %>
            </span>
</p>                
    </a>
        <% else %> <!-- party has no messages -->
<a class="btn btn-inactive" href="<%= party_path(ap) %>">
    
        <p class="largetext">
            
        <% ap.users.each do |pu| %> 
            
        <%= pu.name %>
            
            <% unless pu == ap.users.last %>
            and
            <% end %>
            
        <% end %> <!-- end each user -->
        's session
            <span class="glyphicon glyphicon-chevron-right
"></span>
</p>                
    </a>
        <% end %>
    <% else %>
<% end %>
<% end %>
<% end %>
    <% else %>
    <p>No parties yet! </p>
<% end %>
    </div>

app/views/users/_partyoptions.html.erb
<div class="col-xs-12">
<% if logged_in? %>
<% if @user.id == current_user.id %>
<h2>Your party options</h2>
<p>A party option starts a session with pre-set information. <%= link_to "Create a new party option", new_party_option_path, class: "btn-primary btn-xs" %></p>
    <% @user.party_options.each do |opo| %> 
<div class="result">
<p><%= opo.name %></p>
    <%= link_to "View full details", party_option_path(opo), class: "btn btn-info" %>
<%= link_to "Edit party option", edit_party_option_path(opo), class: "btn btn-warning" %>
    <%= link_to "Delete", party_option_path(opo), method: :delete, data: { confirm: 'Are you certain you want to delete this?' },
class: "btn btn-danger" %>
    <!--- doesn't work /\ -->
</div>
<br />
<% end %>
<p>Your users can also request a game with you:</p>
<% end %>
<% else %>
<h2>Play a game with <%= @user.name %>:</h2>

<% @user.party_options.each do |po| %>     
<div class="party-option-wrapper col-xs-6 col-sm-4 col-md-3">
    <div class="party-option">
    <h3 class="party-option-name"><%= link_to po.name, party_option_path(po) %></h3>
        <div class="profile-cta"><%= link_to "Go >>", party_option_path(po), class: "btn-primary btn-lg" %></div>
        </div>
    </div>

    <% end %> <!-- end party_options.each -->
<% end %>
    <br />
    <div class="col-xs-12">
<p><%= link_to 'Set up a game', new_party_path(:previous_user => @user.id), class: "btn btn-default btn-xs" %> with your own options.</p>
        </div>

</div>

app/views/users/_publicpartyoptions.html.erb
<div id="public-partyoptions" class="col-xs-12">



<h2>Play a game with <%= @user.name %>:</h2>

<% @user.party_options.each do |po| %>     
<div class="party-option-wrapper col-xs-6 col-sm-4 col-md-3">
    <div class="party-option">
    <h3 class="party-option-name"><%= link_to po.name, party_option_path(po) %></h3>
        <div class="profile-cta"><%= link_to "Go >>", party_option_path(po), class: "btn-primary btn-lg" %></div>
        </div>
    </div>

    <% end %> <!-- end party_options.each -->
    
    <%= link_to 'Donate!', new_donation_path(:to_user_id => @user.id), class: "btn btn-primary btn-xl" %>
    
    <p><%= link_to 'Set up a game', new_party_path(:previous_user => @user.id), class: "btn btn-default btn-xs" %> with your own options.</p>

    <br />

</div>

app/views/users/_signup_from_search.html.erb
<!--- complete, all features form. Now only used on edit -->

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
        
      <h3><%= pluralize(@user.errors.count, "error") %>, oh no:</h3>

        <ul><p class="text-warning">
<% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </p>
      </ul>
    </div>
  <% end %>

<form role="form">
  <div class="form-group">
<!--- show only on new -->      

      <div class="col-xs-12 col-sm-6 col-lg-4">
          <h3>Basics</h3>
          <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
      <div class="field">
          <%= f.label :email %><br>
    <%= f.text_field :email  %>
  </div>
  <div class="field">
    <%= f.label :password  %><br>
      <%= f.password_field :password %>
      <p class="smalltext">8 charachters, one uppercase and one lowercase</p>
  </div>
    
    </div> 
    
      
    </div>
    <div class="col-xs-12 actions">
        <%= f.submit "Let's game on", class: "btn btn-primary" %>
    </div>


      </form>

<% end %>

app/views/users/allparties.html.erb
<h2>All your parties<h2>
    
    <a class="btn btn-default" href="<%= user_path(current_user) %>"><span class="glyphicon glyphicon-chevron-left
        "></span> Back to your profile</a>
    
    <% @showmessages = -1 %>
    <%= render 'listparties' %>

app/views/users/edit.html.erb
    <div class="container-fluid">

<h2>This is yo profile</h1>

<%= render 'form' %>
            <div class="col-xs-12 actions">
    </div>

app/views/users/new.html.erb
<%= render 'form' %>

        
<% link_to 'Back', users_path %>

app/views/users/old_index.html.erb
<p id="notice"><%= notice %></p>
<h2>I'm looking for </h2>
Search form by game
<h2>for</h2>
Search form with tags
<br />

<%= link_to "Advanced Search", new_search_path %>

<h2>Find by name</h2>
<%= form_tag users_path, :method => 'get' do %>
    <p>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "go", :name => nil %>
</p>
<% end %>


<h2>Play a game with:</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New User', new_user_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<% content_for :head do %>
<title><%= @user.name %> | Profile <%= title_suffix %></title>
<% end %>
<div class="profile-top">
    <div class="header-content">
  <% unless @user.avatar.blank? %>
    <div class="row user-info">
        <div class="user-image">
        <%= image_tag @user.avatar.profile.url, class: "profile-avatar" %>
            </div>

        </div>
    <% end %>
<div class="profile-header">
<h2><%= @user.name %>    </h2>
    
        <div class="">
<h4><%= @user.about %></h4>
            
            <div class="profile-buttons">
            
<% if current_user.present? %>

    <% if @user.id == current_user.id %>
    <span class="green smalltext">(that's you...)</span>
    <p>
     
    <a class="btn-default btn" style="color: #222" href="<%= edit_user_path(@user) %>">Edit your profile! <span class="glyphicon glyphicon-pencil"></span></a>
        </a>
        </p>
    <% else %>
    <%= link_to 'Game with me! ', new_party_path(:previous_user => @user.id), class: "btn btn-primary" %>
    <% end %>
    <% else %>
    <%= link_to 'Game with me! ', new_party_path(:previous_user => @user.id), class: "btn btn-primary btn-lg " %>
    <% end %>
           </div> 
        </div>

   <%= render 'linkslist' %>
    </div>
</div>
</div>
<!--- end header -->
<div class="profile-body">
    <div class="col-xs-12" id="split">
        <div class="col-sm-6 longdesc">        <p><%= @user.longdesc %></p>
</div>
        <div class="col-sm-6" id="actiongrid">
    <div class="col-xs-12">
<% @user.tags.each do |x| %> 
    <div class="col-xs-2 profile-badge">
        <div class="user-type">
            <p>
            <%= x.name %>
            </p>
        </div>
    </div>
<% end %>
</div>

        </div> 
        <!--- end left --->
<div class="col-sm-12">
    <%= render 'gamelist' %>
</div>
</div>
</div>
<div class="col-xs-12">
    <h3>Your active sessions:</h3>
<% @showmessages = 0 %>
<%= render 'listparties' %>
<a href="/allparties" class="btn btn-default">See all your parties</a>
    </div>
    </div>
</div>