config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :profilelinks
    root 'games#index' 
    
    get 'login' => 'login_sessions#new'
    get 'login' => 'login_sessions#create'
    get 'logout' => 'login_sessions#destroy'
    post 'login' => 'login_sessions#create'
	
	get 'signup' => 'users#new'
    
    get 'privacy' => 'staticpages#privacy'
  	resources :games
    resources :users, :path => "players"
    get 'allparties' => 'users#allparties'
	resources :login_sessions
    resources :tags
    resources :parties do 
    resources :messages
    end
    resources :searches
    resources :profilelinks
    
    get '*path' => redirect('/')
    

end

app/models/game.rb
class Game < ActiveRecord::Base
    has_and_belongs_to_many :users
    has_many :messages

    def to_param
        slug
    end
    
    mount_uploader :game_picture, GamePictureUploader
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
      
          @games = Game.paginate(:page => params[:page], :per_page => 15)
  end

  # GET /games/1
  # GET /games/1.json
  def show
#      @new_message = current_user.messages.build
      
      @game = Game.find_by_slug(params[:id])
      @new_message = @game.messages.build

      respond_to do |format|
          format.html # show.html.erb
          format.json { render json: @game }
  end
end


  # GET /games/new
  def new
		@game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)
      @game.slug =  @game.name.downcase.gsub(" ", "-")
	  
    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
		  
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
        # looks for matching slugs and returns the game
        @game = Game.find_by_slug(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
        params.require(:game).permit(:name, :game_picture, :image_url, :slug)
    end
end

app/helpers/games_helper.rb
module GamesHelper
    
    def gamemessages
       
        gamemessages = []
        gamemessages << @game.messages.all
        
    end
    
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
      <%= f.label :game_picture %><br>
      <%= f.file_field :game_picture %>
  </div> 

<div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</form>

app/views/games/edit.html.erb
<h1>Editing Game</h1>


<% if is_admin? %>
<%= render 'form' %>
<% else %>
<p>uh, you shouldn't be here.</p>
<% end %>


<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>


<div class="splash-hp">
    
<div class="jumbotron app-home">
    <div class="container">
      <div class="right-actions actions-home">
        <a data-toggle="collapse" data-target="#open-controls" ><span class="glyphicon glyphicon-option-vertical
 header-nav home-option"></span>
        </a>
        
        <div id="open-controls" class="collapse">
    <% if logged_in? %>
            <div class="user-action">
<p>
                <%= link_to "Log out", logout_path %>
                </p>
                    </div>
            <div class="user-action">
                <p><%= link_to "Profile", user_path(current_user) %></p>
        </div>
<% else %>
        <div class="user-action">
<p><%= link_to 'Log in', login_path %></p>
        </div>
        <div class="user-action">
<p><%= link_to 'Sign up', new_user_path %></p></div>
        
    <% end %>
        </div>
        </div>
    
<h2 class="green">Better players, better games</h2>
<h4>Find people that game like you do.</h4>
         
    </div>
    
</div>
<% flash.each do |message_type, message| %>
    <div id="message" class="alert alert-<%= message_type %>"><%= message %><%= notice %></div>
      <% end %>
<div class="container search-content">

<br />

<%= will_paginate @game %>
    <p>Chat with gamers or <a href="/searches/new" class="underline">search for someone to play with</a></p>

    
    <% @games.each do |d| %>
    <a href="<%= game_path(d) %>">
    <label class="game-label-cover">
        
        <% if d.image_url.present?  %>
        <div id="game-panel" class="select-panel game-selector">
            

        
        <div class="game-pic">
            <img src="<%= d.image_url %>" class="game-pic">
        </div>
    <div class="">
        <span class="results-text">
        <%= d.name %>
        </span>
        </div>


</div>
        <% else %>
        
        <button class="btn btn-primary"><%= d.name %>
            </button>
        
        <% end %>
    </label>
</a>
    <% end %>

    </div>
    
        <a href="<%= new_search_path %>"class="btn btn-lg btn-primary">Or search for a user</a>

app/views/games/new.html.erb
<h1>New Game</h1>

<% if is_admin? %>
<%= render 'form' %>
<% else %>
<p>uh, you shouldn't be here.</p>
<% end %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<h2><%= @game.name %></h2>
<h3>Chat with other players to arrange a game</h3>
<% content_for :head do %>
<title><%= @game.name %> <%= title_suffix %> | <%= @notifier %></title>
<% end %>
    <div class="">
        <%= form_for @new_message, id: "submitmessage", :url => {:controller => 'messages', :action => 'create', :format => :js}, :remote => true do |c| %>
                        <div class="col-xs-12 col-sm-8 messages">

                    <div class="row">
            <%= c.text_field :body, id: "newmessage",  class: "col-sm-10 col-md-8 col-lg-6 col-xs-10"  %>
        
<%= hidden_field_tag(:thegame, @game.id) %>
            
                        <!-- need to load this on page load -->
                        <%= hidden_field_tag :anon_user_id, truncate(session.id, length: 5, :omission => '' ) %>
        
        <%= c.submit "Send", id: "send", class: "col-xs-2 col-sm-2" %>
        </div>
    <p class="smalltext">Don't give out any personal information - never transfer money or arrange to meet in person.</p>

        <%= sync_new partial: 'message_row', resource: Message.new %>
        
        <!--- older messages -->
        <%= sync partial: 'message_row', collection: @game.messages.order("created_at desc").limit(50),  :formats => [:html] %>

</div>
        
                 <div class="col-xs-12 col-sm-4 messages">
                     <h3>Search</h3>
                     <p>You can also search for registered users and start private messaging:</p>
                     <a href="<%= new_search_path %>" class="btn btn-primary btn-md" action="button">
                     Search
                     </a> 
                   <hr />
                      <p><h3>Example: </h3>
            <p><b>Rick Sanchez:</b> [PC] Need a support player to join stack. 
                <br /><b>Jerry Smith: </b>[XBOX] Looking to play against someone.
        </p>
                     <hr />
                     <p>Sign up to appear in search results</p>

                     <a href="<%= new_search_path %>" class="btn btn-default" action="button">
                     Sign up
                     </a>
        <p class="smalltext">
        Fed up with too many toxic games, I put this together in the hope we can all have better experiences gaming. Give us some feedback! What do you want to see next?
<br /><a href="http://www.twitter.com/gathrgg/">Twitter</a>
            <br /><a href="mailto:joe@gathr.gg">Email</a>
        </p>
                             </div>

            <% end %>
</div>