config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :profilelinks
    root 'games#index' 
    
    get 'login' => 'login_sessions#new'
    get 'login' => 'login_sessions#create'
    get 'logout' => 'login_sessions#destroy'
    post 'login' => 'login_sessions#create'
	
	get 'signup' => 'users#new'
    
    get 'privacy' => 'staticpages#privacy'
  	resources :games
    resources :users, :path => "players"
    get 'allparties' => 'users#allparties'
	resources :login_sessions
    resources :tags
    resources :parties do 
    resources :messages
    end
    resources :searches
    resources :profilelinks
    
    get '*path' => redirect('/')
    

end

app/models/search.rb
class Search < ActiveRecord::Base
    
    def users
    
#        users_g = User.includes(:games).where("games.name LIKE ?", game)  
        users_g = User.includes(:games).where('games.name LIKE ?', "%#{game}%")
#        users_g = User.includes(:games).where("games.name", game)
        
        users_t = User.includes(:tags).where("tags.name" => user_profile_tag)
        
        #       based on search terms present, add the two users or just set them accodrdingly. There won't be a condition where both are blank, as the controller checks for that.
        
        if user_profile_tag.present? && game.present?
            users = users_g.merge(users_t)
#            puts '>>>>'
#            puts 'both search terms return users'
        else
            if game.present?
                users = users_g
#                puts '>>>>'
#                puts 'only games present'        
            end
            
            if user_profile_tag.present?
                users = users_t
#                puts '>>>>'
#                puts 'only tags present'    
            end
        end
        
        return users
                
    end
    
end

#       debug if required : move to funct above display the search criteria
#        
#        puts '*** the game = '
#        puts game
#        
#        puts '*** the tag = '
#        puts user_profile_tag
#        
#               
#        puts '***** USERS with search tag >>'
#        users_t.each do |mlep|
#            puts mlep.name
#        end
#        
#        
#        puts '*** >> USERS with search game'
#        users_g.each do |slep|
#            puts slep.name
#        end
#        puts '***'
#
#       more debug, if ya need it        
#        puts 'results:'
#        users.each do |cka|
#            puts cka.name
#        end
#        puts '<<<'
#        

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

    def new
        @search = Search.new
        @game = User.includes(:game).where(game: { name: @game })
        @user_profile_tag = User.includes(:tag).where(tag: { name: @user_profile_tag })
                
    end
    def create
        if params[:search].nil?
            flash[:danger] = "Oops! Please choose an option"
        return redirect_to root_path(anchor: 'message')
        end
        
        @search = Search.create(search_params)
        redirect_to @search
    end
    
        
    def show
        @search = Search.find(params[:id])
        @search_users = @search.users.all.paginate(:page => params[:page], :per_page => 15)
    end
    
    def index
        @search = Search.paginate(:page => params[:page])
    end

    private
    
    def search_params
        params.require(:search).permit(:game, :user_profile_tag)
    end
end

app/helpers/searches_helper.rb
module SearchesHelper
    def list_games
        gamearray = Array.new
        Game.find_each do |c|
        gamearray << c
        end
        return gamearray
    end

    def list_user_tags
        tagsarray = Array.new
        Tag.find_each do |z|
        tagsarray << z
        end
        return tagsarray
    end
end

app/views/searches/_new.html.erb
<%= form_for @search do |s| %>

<div class="container"><p id="notice"><%= notice %></p></div>
<div class="container search-content">

    <p class="smalltext">Choose a game and what you want to do.</p>
    <div class="row " id="game-selectors">
    
        <% #these need to de-select too #%>
    <% counter = 0 %>
<% list_games.each do |d| %>
    
    <% counter += 1 %>
    <label class="game-label-cover" id="<%= counter %>">
<div class="status-cover green">
        <span id="selected-status<%= counter %>" class="game-select-span"></span>
        </div>
    <div id="game-panel<%= counter %>" class="select-panel game-selector">
            

        
        <div class="game-pic">
            <% image_tag d.game_picture, class: "game-pic#{counter}" %>
            <img src="<%= d.image_url %>">
        </div>

        <%= s.radio_button :game, d.name, class: "gamechoice-invis-checkbox each-button", id: "game-button#{counter}" %>
    <br />

</div>
    <div class="select-label">
        <%= s.label :game, d.name, class: "game-name", id: "#{counter}" %>
        </div>
    </label>
    
    <% end %>

        <div class="col-xs-12 col-md-8 col-md-offset-2">
            <p><%= s.text_field :game, placeholder: "Other...", class: "other-game text-entry" %></p>
        </div>

    </div>
    <div class="breaker"></div>
<div class="row">

<% tcount = 0 %>
<% list_user_tags.each do |tag| %>
<% tcount += 1 %>
    <label class="tag-label-cover" id="<%= tcount %>">
        <div id="tag-panel<%= tcount %>" class="select-panel tag-selector">
            <div class="status-cover green">
        <span id="tag-selected-status<%= tcount %>"></span>
        </div>
            <%= s.radio_button :user_profile_tag, tag.name, class: "each-button", id: "#{tcount}" %>

            
                <div class="select-label">
<%= s.label :user_profile_tag,
tag.display_name, class: "tag-name" %>
            </div>
<span class="<%= tag.icon %> hp-feat-icon"></span>

        </div>
</label>
    <% end %>
</div>
    <div class="submit">
<%= s.submit "Go", :class => "btn btn-primary btn-lg" %>

        </div>
<% end %>
</div>

app/views/searches/_reg_nav.html.erb
<div class="homepage-nav jumbotron">
    <h2>Hey <%= current_user.name %></h2>
    
    <p>You can:</p>
    <nav>
        <%= link_to "Log out", logout_path, class: "btn btn-default"   %>
        <%= link_to "View profile", user_path(current_user), class: "btn btn-default"  %>
        <%= link_to "Edit profile", edit_user_path(current_user), class: "btn btn-default"  %>
        <%= link_to "Start a session", new_party_path, class: "btn btn-default"  %>
    </nav>
</div>
<% flash.each do |message_type, message| %>
    <div id="message" class="alert alert-<%= message_type %>"><%= message %><%= notice %></div>
      <% end %>

<h2 class="msg">Or find new players:</h2>

app/views/searches/_static.html.erb
            <div class="intro-hp">
                <div class="describer">
<h3 class="landing-h3"><span class="green lrg">Gathr</span> is a platform to connect gamers.</h3>
                    <p class="homepage-desc">For all games and players, we believe <span class="green"> gaming is better together </span></p>
            
              </div>
                    <div class="cta-holder">
<div class="primary-cta">
                         <a href="explainer" class="hp-cta btn btn-default" role="button">
                
            
                <h3>Learn more
                 <span class="homepage-glyph glyphicon glyphicon-menu-right

" aria-hidden="true"></span>
                    </h3>
                </a> 
                        </div>
                        
                        <div class="hp-navigation">
                        
            <a href="#search" class="on-page-navigation">
               <button class="hp-cta btn btn-default">
                
                
                <h3>Get lessons
                 <span class="homepage-glyph glyphicon glyphicon-menu-down

" aria-hidden="true"></span>
                    </h3>
                
                </button>
                            </a>

           <a href="#search" class="on-page-navigation">
               <button class="hp-cta btn btn-default">
                
                
                <h3>Find team mates
                 <span class="homepage-glyph glyphicon glyphicon-menu-down

" aria-hidden="true"></span>
                    </h3>
               </button>
                </a>
                            
  <a href="#search" class="on-page-navigation">
               <button class="hp-cta btn btn-default">               
                
                <h3>Discover streamers
                 <span class="homepage-glyph glyphicon glyphicon-menu-down

" aria-hidden="true"></span>
                    </h3>
                    </button>
                </a>
                        
                  

                        </div>
</div>
        </div>
                <a href="/what-is-it">
    <div class="streamer-yt">
        
<h3>I am a Streamer or YouTuber
            <button type="button" class="btn btn-default btn-home" aria-label="Left Align"><span class="green glyphicon glyphicon-chevron-right
" aria-hidden="true"></span>
    </button>
    </h3>
        </div>
</a>
    </div>
<% flash.each do |message_type, message| %>
    <div id="message" class="alert alert-<%= message_type %>"><%= message %><%= notice %></div>
      <% end %>

    </div>
<div id="search"></div>
<h2 class="msg">Better gaming is a few clicks away.</h2>

app/views/searches/index.html.erb
<% @search.each do |l| %>

<p><%= l.id %> | <%= l.game %></p>


<% end %>

<%= will_paginate @search %>

app/views/searches/new.html.erb
<div class="splash-hp">
    
<div class="jumbotron app-home">
    <div class="container">
      <div class="right-actions actions-home">
        <a data-toggle="collapse" data-target="#open-controls" ><span class="glyphicon glyphicon-option-vertical
 header-nav home-option"></span>
        </a>
        
        <div id="open-controls" class="collapse">
    <% if logged_in? %>
            <div class="user-action">
<p>
                <%= link_to "Log out", logout_path %>
                </p>
                    </div>
            <div class="user-action">
                <p><%= link_to "Profile", user_path(current_user) %></p>
        </div>
<% else %>
        <div class="user-action">
<p><%= link_to 'Log in', login_path %></p>
        </div>
        <div class="user-action">
<p><%= link_to 'Sign up', new_user_path %></p></div>
        
    <% end %>
        </div>
        </div>
    
<h2 class="green">Better players, better games</h2>
<h4>Find people that game like you do.</h4>
         
    </div>
    
</div>
<% flash.each do |message_type, message| %>
    <div id="message" class="alert alert-<%= message_type %>"><%= message %><%= notice %></div>
      <% end %>
<% if logged_in? %>
<% render 'reg_nav' %>
<% else %>
<% render 'static' %>
<% end %>
<%= render 'new' %>

app/views/searches/show.html.erb
<% content_for :head do %>
<title>Search <%= title_suffix %></title>
<% end %>
<h2>Results</h2>
<p id="notice"><%= notice %></p>

<h3>
<% if @search.game.present? %>

    People playing <span class="green"><%= @search.game %></span>
    <% end %>
<% if @search.user_profile_tag.present? && @search.game.present? %>
who are
    <% end %>
    <% if @search.user_profile_tag.present? %>
    <span class="green"><%= @search.user_profile_tag %></span>
    <% end %>    
      
</h3>
<% unless logged_in? %>
<h4>Be listed here: <a href="/signup" style="color: #222;">Sign up!</a></h4>
<% end %>
<% if @search.users.empty? %>
<p>No one yet! Sign up and be the first.</p>
<% end %>

<% unless @search.users.empty? %>

<div class="results">
    
    <% @search_users.each do |m| %>
    
    <a href="<%= url_for(m) %> ">
        <div class="col-xs-6 col-sm-3 col-lg-2">
            <div class="result">
            <div class="user-image">
            <% if m.avatar.blank? %>
<img src="/default-picture.png">
            <% else %>
            <%= image_tag m.avatar.profile.url %>
            
            <% end %>
            </div>
            <h3><%= link_to m.name, m, :class => "results-text" %></h3>
            <p><%= m.about %></p>
                <%= link_to 'Set up a game', new_party_path(:previous_user => m.id), class: "btn btn-primary" %>
        
          </div>
          </div>
        </a>
    <% end %> <!-- end each users -->
    </div>

    <% end %>
  </div>  
    <div class="actions col-xs-12">
        <%= will_paginate @search_users %>
<p>View profile to start a game!</p>

<p><%= link_to "Search again",new_search_path %>
    </p></div>
<br />