config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :profilelinks
    root 'games#index' 
    
    get 'login' => 'login_sessions#new'
    get 'login' => 'login_sessions#create'
    get 'logout' => 'login_sessions#destroy'
    post 'login' => 'login_sessions#create'
	
	get 'signup' => 'users#new'
    
    get 'privacy' => 'staticpages#privacy'
  	resources :games
    resources :users, :path => "players"
    get 'allparties' => 'users#allparties'
	resources :login_sessions
    resources :tags
    resources :parties do 
    resources :messages
    end
    resources :searches
    resources :profilelinks
    
    get '*path' => redirect('/')
    

end

app/models/profilelink.rb
class Profilelink < ActiveRecord::Base
    before_validation :smart_add_url_protocol
    belongs_to :user
    
    validates :user_id, presence: true

        
protected
    def smart_add_url_protocol
        puts ">>>"
        puts "running url checker"
        unless self.url.blank?
        unless self.url[/\Ahttp:\/\//] || self.url[/\Ahttps:\/\//]
      self.url = "http://#{self.url}"
  end
  end
end
    
end

app/controllers/profilelinks_controller.rb
class ProfilelinksController < ApplicationController
  before_action :set_profilelink, only: [:show, :edit, :update, :destroy]

  # GET /profilelinks
  # GET /profilelinks.json

  # GET /profilelinks/1
  # GET /profilelinks/1.json
  def show
  end

  # GET /profilelinks/new
  def new
    @profilelink = Profilelink.new
  end

  # GET /profilelinks/1/edit
  def edit
  end

  # POST /profilelinks
  # POST /profilelinks.json
  def create
    @profilelink = Profilelink.new(profilelink_params)

    respond_to do |format|
      if @profilelink.save
          format.html { redirect_to user_path(id: (@profilelink.user.id))}
        format.json { render :show, status: :created, location: @profilelink }
          
          flash[:success] = "Created a link."
          
      else
        format.html { render :new }
        format.json { render json: @profilelink.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profilelinks/1
  # PATCH/PUT /profilelinks/1.json
  def update
  end

  # DELETE /profilelinks/1
  # DELETE /profilelinks/1.json
  def destroy
    @profilelink.destroy
    respond_to do |format|
      format.html { redirect_to user_path(id: (@profilelink.user.id))}
          
        flash[:warning] = "Deleted link."
        
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profilelink
      @profilelink = Profilelink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profilelink_params
        params.require(:profilelink).permit(:url, :name, :user_id).merge(user_id: current_user.id)
    end
end

app/helpers/profilelinks_helper.rb
module ProfilelinksHelper
end

app/views/profilelinks/_form.html.erb
<%= form_for(@profilelink) do |c| %>
  <% if @profilelink.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profilelink.errors.count, "error") %> prohibited this profilelink from being saved:</h2>

      <ul>
      <% @profilelink.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
      <%= c.label "Web link" %><br>
    <%= c.text_field :url %>
  </div>

  <div class="field">
      <%= c.label "What type of link is this?" %><br>
      <% @labels = ["Twitch", "Twitter", "YouTube", "Website", "Stats", "Steam", "Other" ] %>
      <%= c.collection_select :name, @labels, :to_s, :to_s %> 
  </div>

  <div class="actions">
    <%= c.submit %>
  </div>
<% end %>

app/views/profilelinks/edit.html.erb
<h1>Editing Profilelink</h1>

<%= render 'form' %>

<%= link_to 'Show', @profilelink %> |
<%= link_to 'Back', profilelinks_path %>

app/views/profilelinks/new.html.erb
<h1>New Profilelink</h1>

<%= render 'form' %>

<%= link_to 'Back', profilelinks_path %>